export type Language = "en" | "es";
export type Art = "atlas" | "signal" | "garden" | "orbit";
export interface Project {
  id: string;
  title: string;
  category: Record<Language, string>;
  description: Record<Language, string>;
  note: Record<Language, string>;
  url: string;
  art: Art;
  tags: string[];
  status: Record<Language, string>;
}

export const identity = {
  name: "Jesús Rubio Sainz",
  github: "https://github.com/jrubiosainz",
  linkedin: "https://www.linkedin.com/in/jrubiosainz/",
  huggingface: "https://huggingface.co/jrubiosainz",
  site: "https://jrubiosainz.github.io",
};

export const projects: Project[] = [
  {
    id: "notebook-quest",
    title: "Notebook Quest",
    category: { en: "01 — A doodle with a destiny", es: "01 — Un garabato con destino" },
    description: {
      en: "An entire adventure, hiding in the margins. A notebook doodle becomes the hero of an original turn-based iOS RPG.",
      es: "Una aventura entera escondida en los márgenes. Un garabato de cuaderno se convierte en el héroe de un RPG original por turnos para iOS.",
    },
    note: {
      en: "Swift combat systems meet an AI-art pipeline designed to keep every character and scene in the same visual world.",
      es: "Sistemas de combate en Swift y un flujo de arte con IA que mantiene a personajes y escenarios dentro de una misma identidad visual.",
    },
    url: "https://github.com/jrubiosainz/notebookgame",
    art: "atlas",
    tags: ["Swift", "iOS", "AI art"],
    status: { en: "Source-code adventure", es: "Aventura en código" },
  },
  {
    id: "agentmon",
    title: "Agéntmon",
    category: { en: "02 — A different kind of AI adventure", es: "02 — Otra forma de vivir la IA" },
    description: {
      en: "What if the creatures were robots, and the gyms were datacentres? A robot-collecting adventure with the soul of a handheld classic.",
      es: "¿Y si las criaturas fueran robots y los gimnasios, centros de datos? Una aventura de colección de robots con alma de consola portátil.",
    },
    note: {
      en: "A custom TypeScript canvas engine, turn-based battles, and a world built from pixel-sized ideas. Explore the public first-generation source.",
      es: "Un motor propio en TypeScript y canvas, combates por turnos y un mundo construido con ideas del tamaño de un píxel. Explora el código público de la primera versión.",
    },
    url: "https://github.com/jrubiosainz/agentmon",
    art: "orbit",
    tags: ["TypeScript", "Canvas 2D", "Pixel art"],
    status: { en: "First-generation public source", es: "Código público de la primera versión" },
  },
  {
    id: "microduck",
    title: "Microduck",
    category: { en: "03 — Small robot. Good manners.", es: "03 — Robot pequeño. Buenos modales." },
    description: {
      en: "A little room for someone else. Experiments in following, yielding, and the surprisingly human etiquette of sharing a space.",
      es: "Un poco de espacio para los demás. Experimentos sobre seguir a personas, ceder el paso y la sorprendente humanidad de compartir un lugar.",
    },
    note: {
      en: "Built on Pollen Robotics' Mini BDX, using existing ONNX locomotion policies to explore what the robot should do next.",
      es: "Sobre Mini BDX de Pollen Robotics, con políticas de locomoción ONNX existentes para explorar qué debería hacer el robot a continuación.",
    },
    url: "https://github.com/jrubiosainz/microduck",
    art: "garden",
    tags: ["Python", "MuJoCo", "ONNX"],
    status: { en: "Simulation study", es: "Estudio en simulación" },
  },
  {
    id: "reachy-mini",
    title: "Talkie Gentleman",
    category: { en: "04 — Reachy Mini Playground", es: "04 — Experimentos con Reachy Mini" },
    description: {
      en: "A 1920s gentleman in a robot's body. Talkie Gentleman explores how voice, character, and expressive movement can turn a response into a presence.",
      es: "Un caballero de los años veinte en el cuerpo de un robot. Talkie Gentleman explora cómo la voz, la personalidad y el movimiento convierten una respuesta en una presencia.",
    },
    note: {
      en: "Part of a playground of robot personalities, gesture mirroring, and music controls. Built with the Reachy Mini SDK.",
      es: "Parte de una colección de personalidades robóticas, imitación de gestos y control musical. Creado con el SDK de Reachy Mini.",
    },
    url: "https://huggingface.co/spaces/jrubiosainz/talkie_gentleman",
    art: "signal",
    tags: ["Python", "Reachy Mini", "Whisper"],
    status: { en: "App code & simulation demos", es: "Código y demos en simulación" },
  },
];

export const experiments = [
  {
    title: "Manga 3D Color",
    description: { en: "Flat pages. A new dimension. Colour, depth, and a parallax reading experience.", es: "Páginas planas. Otra dimensión. Color, profundidad y lectura con efecto de paralaje." },
    url: "https://github.com/jrubiosainz/manga-3d-color",
    type: { en: "VISUAL EXPERIMENT", es: "EXPERIMENTO VISUAL" },
  },
  {
    title: "Deduku",
    description: { en: "A deduction puzzle where not every witness is telling the truth.", es: "Un puzle de deducción donde no todos los testigos dicen la verdad." },
    url: "https://jrubiosainz.github.io/deduku/",
    type: { en: "PLAY IN YOUR BROWSER", es: "JUEGA EN EL NAVEGADOR" },
  },
  {
    title: "Snorkel Checklist",
    description: { en: "Turn underwater sightings into your own personal aquarium.", es: "Convierte tus avistamientos submarinos en un acuario personal." },
    url: "https://jrubiosainz.github.io/snorkel-checklist/",
    type: { en: "EXPLORE THE APP", es: "EXPLORA LA APLICACIÓN" },
  },
];

export const en = {
  metaTitle: "Jesús Rubio Sainz — Imagination, compiled.",
  metaDescription: "Cloud Solution Architect, AI & Apps at Microsoft. Exploring the space between human imagination and what code can make real. Meet Jesús Rubio Sainz.",
  skip: "Skip to content",
  navLabel: "Chapters",
  home: "Back to the beginning",
  build: "The build",
  work: "Selected work",
  about: "The human",
  contact: "Let's talk",
  languageLabel: "Language compiler",
  languageCommand: "Recompile this world",
  languageHint: "Same imagination. Another language.",
  languageCurrent: "Current language",
  languageEnglish: "Read in English",
  languageSpanish: "Leer en español",
  motionOn: "Motion on",
  motionOff: "Motion off",
  motionLabel: "Enable animation",
  introLabel: "A personal experiment in possibility",
  role: "Cloud Solution Architect",
  roleDetail: "AI & Apps at Microsoft",
  heroFirst: "IMAGINATION,",
  heroSecond: "COMPILED.",
  heroDescription: "Somewhere between a curious thought and a working thing.",
  heroPersonal: "I'm Jesús. I connect AI, apps, and a little imagination to build what comes next.",
  explore: "Step inside",
  heroAside: "An idea, before it knows\nwhat it wants to be.",
  companionName: "Meet Miga",
  companionType: "A small courier of big ideas",
  edition: "Human curiosity. Machine possibility.",
  scroll: "Scroll to compile",
  introIndex: "01 / THE BUILD",
  buildTitle: "Every world starts\nwith a little “what if”.",
  buildDescription: "A thought becomes a sketch. A sketch becomes a system. And, line by line, something that didn't exist starts looking back.",
  buildHint: "Your scroll is the playhead. Go back. Take it apart.",
  buildFilename: "a-little-what-if.ts",
  buildStatus: "Imagination engine",
  buildPhase0: "01 / A little structure",
  buildPhase1: "02 / Room to explore",
  buildPhase2: "03 / A new perspective",
  buildPhase3: "04 / A spark of possibility",
  buildComplete: "Idea made tangible.",
  buildStatic: "The complete idea. No motion required.",
  buildFootnote: "Original SVG. Real animation code. No borrowed universe.",
  output: "OUTPUT / MIGA",
  workIndex: "02 / SELECTED WORK",
  workTitle: "Curiosity,\nin the wild.",
  workDescription: "Small experiments. Unexpected connections. Things made because “what if” is a very good place to start.",
  moreTitle: "There is always another “what if”.",
  moreLabel: "ALSO ON THE WORKBENCH",
  reachyTitle: "A little more human.",
  projectLink: "Explore the source",
  projectArtLabel: "Original illustration inspired by the project, not a product screenshot",
  allWork: "More experiments on GitHub",
  source: "Public source",
  aboutIndex: "03 / THE HUMAN",
  aboutTitle: "Serious about the craft.\nNot too serious about myself.",
  aboutLead: "Hello again.\nI'm Jesús.",
  aboutDescription: "I'm Jesús Rubio Sainz, a Cloud Solution Architect for AI & Apps at Microsoft. I explore what happens when AI meets the world beyond the chat window — from expressive robots to games, visual experiments, and useful little apps.",
  fieldNote: "A field note from 2023",
  fieldNoteText: "Sharing the wonder: my phone-screen demonstration of Stable Diffusion Turbo, a tool by Stability AI.",
  fieldNoteLink: "Watch the original LinkedIn post",
  philosophyTitle: "The way I see it",
  philosophy: "The interesting part isn't just what technology can do. It's what we choose to make with it.",
  anchorOne: "Think like a human.",
  anchorOneText: "Start with the person on the other side of the screen.",
  anchorTwo: "Build to understand.",
  anchorTwoText: "The best way to explore an idea is to give it a shape.",
  anchorThree: "Leave room for wonder.",
  anchorThreeText: "Useful can be playful. Technical can be beautiful.",
  professional: "The professional story",
  profileLink: "Find me on LinkedIn",
  creditsIndex: "04 / THE NEXT CHAPTER",
  creditsTitle: "The best ideas\nstart with hello.",
  creditsDescription: "An interesting problem, a wild possibility, or just a conversation. I'm listening.",
  creditsRole: "Curiosity & code",
  creditsArt: "Original world & companion",
  creditsArtValue: "Drawn in code. Built for this story.",
  creditsThanks: "And you",
  creditsThanksValue: "For making it this far.",
  closing: "End of page. Not the possibilities.",
  replay: "Replay the build",
  backTop: "Back to the opening",
  independent: "A personal website. Views are my own, not Microsoft's.",
  madeWith: "Made of code & curiosity",
  progress: "Reading progress",
};

export const es: typeof en = {
  metaTitle: "Jesús Rubio Sainz — Imaginación, compilada.",
  metaDescription: "Arquitecto de Soluciones Cloud, IA y Aplicaciones en Microsoft. Explorando el espacio entre la imaginación y lo que el código puede hacer realidad. Conoce a Jesús Rubio Sainz.",
  skip: "Saltar al contenido",
  navLabel: "Capítulos",
  home: "Volver al principio",
  build: "La construcción",
  work: "Proyectos",
  about: "La persona",
  contact: "Hablemos",
  languageLabel: "Compilador de idiomas",
  languageCommand: "Recompila este mundo",
  languageHint: "La misma imaginación. Otro idioma.",
  languageCurrent: "Idioma actual",
  languageEnglish: "Read in English",
  languageSpanish: "Leer en español",
  motionOn: "Movimiento sí",
  motionOff: "Movimiento no",
  motionLabel: "Activar animaciones",
  introLabel: "Un experimento personal sobre lo posible",
  role: "Arquitecto de Soluciones Cloud",
  roleDetail: "IA y Aplicaciones en Microsoft",
  heroFirst: "IMAGINACIÓN,",
  heroSecond: "COMPILADA.",
  heroDescription: "Entre una idea curiosa y algo que ya funciona.",
  heroPersonal: "Soy Jesús. Conecto IA, aplicaciones y un poco de imaginación para construir lo que viene.",
  explore: "Pasa y explora",
  heroAside: "Una idea, antes de saber\nqué quiere llegar a ser.",
  companionName: "Te presento a Miga",
  companionType: "Una pequeña mensajera de grandes ideas",
  edition: "Curiosidad humana. Posibilidad artificial.",
  scroll: "Desliza para compilar",
  introIndex: "01 / LA CONSTRUCCIÓN",
  buildTitle: "Todo mundo empieza\ncon un pequeño «¿y si…?».",
  buildDescription: "Una idea se convierte en boceto. Un boceto, en sistema. Y, línea a línea, algo que no existía empieza a devolverte la mirada.",
  buildHint: "El scroll marca el ritmo. Retrocede. Desmóntalo.",
  buildFilename: "un-pequeno-y-si.ts",
  buildStatus: "Motor de imaginación",
  buildPhase0: "01 / Un poco de estructura",
  buildPhase1: "02 / Espacio para explorar",
  buildPhase2: "03 / Una nueva perspectiva",
  buildPhase3: "04 / Una chispa de posibilidad",
  buildComplete: "Una idea que ya puedes tocar.",
  buildStatic: "La idea completa. Sin necesidad de movimiento.",
  buildFootnote: "SVG original. Código de animación real. Un universo propio.",
  output: "RESULTADO / MIGA",
  workIndex: "02 / PROYECTOS",
  workTitle: "La curiosidad,\nsuelta por ahí.",
  workDescription: "Pequeños experimentos. Conexiones inesperadas. Cosas que nacen porque «¿y si…?» es un buen punto de partida.",
  moreTitle: "Siempre queda otro «¿y si…?».",
  moreLabel: "TAMBIÉN EN LA MESA DE TRABAJO",
  reachyTitle: "Un poco más humano.",
  projectLink: "Explora el código",
  projectArtLabel: "Ilustración original inspirada en el proyecto; no es una captura del producto",
  allWork: "Más experimentos en GitHub",
  source: "Fuente pública",
  aboutIndex: "03 / LA PERSONA",
  aboutTitle: "El trabajo, muy en serio.\nA mí mismo, no tanto.",
  aboutLead: "Hola de nuevo.\nSoy Jesús.",
  aboutDescription: "Soy Jesús Rubio Sainz, Arquitecto de Soluciones Cloud de IA y Aplicaciones en Microsoft. Exploro lo que ocurre cuando la IA sale de la ventana del chat: robots expresivos, juegos, experimentos visuales y pequeñas aplicaciones útiles.",
  fieldNote: "Una nota de campo de 2023",
  fieldNoteText: "Compartiendo el asombro: mi demostración, grabada en el móvil, de Stable Diffusion Turbo, una herramienta de Stability AI.",
  fieldNoteLink: "Ver la publicación original en LinkedIn",
  philosophyTitle: "Mi forma de verlo",
  philosophy: "Lo interesante no es solo lo que la tecnología puede hacer. Es lo que decidimos crear con ella.",
  anchorOne: "Piensa como una persona.",
  anchorOneText: "Empieza por quien está al otro lado de la pantalla.",
  anchorTwo: "Construye para entender.",
  anchorTwoText: "La mejor forma de explorar una idea es darle forma.",
  anchorThree: "Deja espacio al asombro.",
  anchorThreeText: "Lo útil puede ser divertido. Lo técnico, bonito.",
  professional: "Mi historia profesional",
  profileLink: "Encuéntrame en LinkedIn",
  creditsIndex: "04 / EL SIGUIENTE CAPÍTULO",
  creditsTitle: "Las mejores ideas\nempiezan con un hola.",
  creditsDescription: "Un problema interesante, una posibilidad inesperada o simplemente una conversación. Te escucho.",
  creditsRole: "Curiosidad y código",
  creditsArt: "Mundo y compañera originales",
  creditsArtValue: "Dibujados con código. Creados para esta historia.",
  creditsThanks: "Y tú",
  creditsThanksValue: "Por haber llegado hasta aquí.",
  closing: "La página termina. Las posibilidades, no.",
  replay: "Repite la construcción",
  backTop: "Volver al comienzo",
  independent: "Una web personal. Mis opiniones no representan a Microsoft.",
  madeWith: "Hecho de código y curiosidad",
  progress: "Progreso de lectura",
};

export const copy = { en, es };
